#!/bin/bash

# Tpkg: a simple shell-script package manager and a fork
# no automatic dependency resolution abilities
#     (kind of similar to Slackware's)
#
# Forked by Halal Noob

url="example.com"        # repository URL example
srctype="net"            # can be either "net" or "dir" (unused for now)
root="/home/richard/root"    # fake root directory. must be absolute path

cd "$root"        # change directory to relative root

if [ "$(pwd)" != "$root" ]; then
    echo "failed to change directory to root prefix"
    exit 1
fi

list_files() {
    if [ "$1" = "listfiles" ]; then
        if [ "$2" != "" ]; then
            # Paket dosyalarını listeleme işlemleri buraya eklenecek
            # Örneğin: cat "/path/to/package/directory/$2/$PKG_FILELIST"
        else
            echo "Please provide a package name to list its files."
        fi
    fi
}

remove_package() {
    if [ "$1" = "remove" ]; then
        if [ "$2" != "" ]; then
            echo -n "Are you sure you want to remove $2?[y/n]: "
            read ans
            if [ "$ans" = "y" ]; then
                # Kaldırma işlemleri burada yer alacak
                # Gerekli komutlar ve işlemler eklenecek
            fi
        else
            echo "Please specify a package to remove."
        fi
    fi
}

verify_package() {
    local pkgname="$1"

    if [ ! -f "/path/to/package/directory/$pkgname/$PKG_FILELIST" ]; then
        echo "$pkgname: No such package in the database."
        return 1
    fi

    # checking packet accuracy

}

if [ "$1" = "install" ]; then
    if [ "$2" = "" ]; then
        echo "you need to specify a package to install"
        exit 1
    elif [ -d "usr/tdb/$2" ]; then
        echo "$2 is already installed"
        exit 1
    fi

    busybox wget -cq "$url/$2.tar"    # get package from url

    if [ "$?" = "0" ]; then    # judge the return value of busybox
        tar -xf "$2.tar"
        rm "$2.tar"
        echo "install ok"

        # Log function: create a log file with installed.txt
        if [ ! -d "/home/$(whoami)/.tpkg/" ]; then
            mkdir -p "/home/$(whoami)/.tpkg/"
        fi

        if [ ! -f "/home/$(whoami)/.tpkg/installed.txt" ]; then
            touch "/home/$(whoami)/.tpkg/installed.txt"
        fi

        echo "$2 installed at $(date)" >> "/home/$(whoami)/.tpkg/installed.txt"
    else
        echo "install failed"
        exit 1
    fi

elif [ "$1" = "" ]; then
    echo "no actions specified"
    exit 1
fi
